# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/study_vivado_ps/zc706_eth_DMA_Loopback/zc706.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_5/design_1_dds_compiler_0_5.xci
# IP: The module: 'design_1_dds_compiler_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/study_vivado_ps/zc706_eth_DMA_Loopback/zc706.gen/sources_1/bd/design_1/ip/design_1_dds_compiler_0_5/design_1_dds_compiler_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/study_vivado_ps/zc706_eth_DMA_Loopback/zc706.srcs/sources_1/bd/design_1/ip/design_1_dds_compiler_0_5/design_1_dds_compiler_0_5.xci
# IP: The module: 'design_1_dds_compiler_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/study_vivado_ps/zc706_eth_DMA_Loopback/zc706.gen/sources_1/bd/design_1/ip/design_1_dds_compiler_0_5/design_1_dds_compiler_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_dds_compiler_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
